### ISSUE TITLE
[Grafana] add support for install from deb url

### ISSUE THREAD

**Issue by bcho** [manala/ansible-roles#229]
Grafana provides pre-packaged deb file, can we add a variable check (like `when manala_grafana_deb_url is defined`) to install from external deb url? (Becuase the upstream version in ubuntu is pretty old, for example: 2.6 in 16.04)

**Comment by nervo** [comment]
@bcho we have splitted manala roles by responsibilities.
As spotted in the `README.md` (https://github.com/manala/ansible-roles/blob/master/manala.grafana/README.md#requirements) you *should* use manala apt role to define official grafana debian repositories as sources.

Tell me if you encounter any issues, so that we can enhance some parts of documentation :)

**Comment by bcho** [comment]
Alright, this approach solves my problem 👍
